spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
#  datasource:
#    url: jdbc:mysql://localhost:3306/switchcon
#    username: root
#    password: 1234
#    driver-class-name: com.mysql.cj.jdbc.Driver